CFLAGS=-Wall -Wextra -std=c11 -pedantic -ggdb

heap: main.c
	$(CC) $(CFLAGS) -o heap main.c

dynamic: dynamic_arrays.c
	$(CC) $(CFLAGS) -o dynamic dynamic_arrays.c

test: test.c
	$(CC) $(CFLAGS) -o ttt test.c
